### ISSUE TITLE
Unable to login in on Android to local server without https

### ISSUE THREAD

**Issue by matthewbaa** [ankicommunity/docker-anki-sync-server#1]
Hi again István,

The client is AnkiDroid 2.11.3, whilst the server is running a self-built image for my Pi's ARM architecture, following your response to https://github.com/kuklinistvan/docker-anki-sync-server/issues/11. 

The server is confirmed to be accessible on the local network through 192.168.x.x, if I try `curl 192.168.x.x`, it returns `Anki Sync Server`, as expected. However, after setting up an account and trying to login on AnkiDroid:

If the `Sync url` is set as `https://192.168.x.x:27701/`, trying to login returns the following dialog box: 
`SSLException while building HttpClient`, which is likely because 192.168.x.x doesn't support https.

Ok, let's set `Sync url` as `http://192.168.x.x:27701/` instead. Trying to login now returns the following dialog box:
`java.net.UnknownServiceException: CLEARTEXT communication to 192.168.x.x not permitted by network security policy`. After a search or two, I think either Android (I'm using Android 10) or AnkiDroid are enforcing https on login.

This may be an issue due to connecting to a 192.168.x.x address instead of an 127.0.0.1 address, perhaps Android or AnkiDroid allow http login on 127.0.0.1 but not 192.168.x.x. But, I can't access 127.0.0.1 from devices other than my Pi.

As far as I'm aware, I cannot add https to 192.168.x.x as it's not a domain. The best case scenario would be able to login without https as I have no need for it.

The only solution I can think of is to setup a reverse proxy to a domain and add https to the domain, but it sounds like a very roundabout way of solving it.

Any advice?

**Comment by plewin** [comment]
AnkiDroid allows non https communication only to localhost (ref https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/res/xml/network_security_config.xml)

It is not required to have a domain to generate a SSL certificate, https://192.168.x.x can work with your own CA. Home routers sometimes have self generated certificates so you can configure them with https://192.168.x.x
No public CA would certify such an address so you need your own certificate.

The options I see for your issue are :
* Hack / rebuild Ankidroid so it allows non https communication
* Setup a reverse proxy or a local port forwarding directly in your android (as unencrypted is allowed for localhost there is no https)
* Setup a https reverse proxy for https://192.168.x.x using a self signed certificate, you might need to add the custom certificate in your phone trusted ca

**Comment by kuklinistvan** [comment]
Hello there! Sorry for the long delay, I did not get a notification for some reason. I'll get back to you soon!

**Comment by kuklinistvan** [comment]
Hello again!
@matthewbaa,
Keep in mind that the currently supported AnkiDroid version is 2.9.1 - you may give that a try.

If I understand correctly, the new version does not allow plain unencrypted http connections - at least according to the references of @plewin. (thank you for linking these!) Also, I think they have pointed out most of your options.

Either you may set up a local dns server on your lan and a self-signed CA (which you'll need to import into Android, hoping that AnkiDroid uses the system certificate store for validating certificates), or you create a patch for AnkiDroid to allow non-https communication.

I think that it would be the more appropriate and simple to patch the app in this case, provided that we have the original source code. I only did a quick lookup, but if you're lucky, there is a chance that changing an option in the manifest and rebuilding the application could solve your issue ([ref]).

[ref]: https://stackoverflow.com/a/50834600

**Comment by matthewbaa** [comment]
Thank you all! I think I'll edit the manifest and rebuild the application, if not, I'll try the other methods.

I'll reopen if all else fails. :)
