### ISSUE TITLE
Suggestion: add an Healthy Check in the Dockerfile

### ISSUE THREAD

**Issue by memiks** [ankicommunity/docker-anki-sync-server#4]
Hi Community,

I added a HEALTHCHECK test to the docker image by included this line at the end of Dockerfile:

```
HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget -q -O - http://127.0.0.1:27701/ || exit 1
```

This check every 30s if server is up and let 3s to respond.
I think it could be good to add it directly in the Dockerfile.

Best Regards,
Memiks.

**Comment by kuklinistvan** [comment]
Hello there,

Thank you for contacting! Yeah, good idea, it makes detecting errors easier. I'm adding that line soon.

István

**Comment by kuklinistvan** [comment]
I've added the line - please reopen the issue if you experience problems.
