### ISSUE TITLE
Will it work on newest version on of Anki desktop? 

### ISSUE THREAD

**Issue by kaharjan** [ankicommunity/docker-anki-sync-server#5]
After setting up my Anki server by going through docker-anki-sync-server, recently I upgraded my Anki server to https. Since then the latest AnkiDroid (2.12.1) works perfect, right now I am wondering could I upgrade my AnkiDesktop(Version 2.1.19) to the latest version? is there anyone has done ?
Thank you!

**Comment by kuklinistvan** [comment]
Hello @kaharjan,

Unfortunately, **it is not expected to work**, but miracles may always happen.

@genedan has mentioned recently that he could get the server working with desktop client version 2.1.26. This is far from official, though, as we are struggling with heavier protocol changes in the clients.

You can learn more on this on our [Gitter](https://gitter.im/ankicommunity/community) and [here](https://github.com/tsudoko/anki-sync-server/issues/70).

You are also welcome to test what works and what does not with the new versions and leave a log here for later. If you have the time and wish to do so, [please check these bullet points](https://github.com/ankicommunity/docker-anki-sync-server/blob/master/Testing.md). 

Thank you for contacting!

**Comment by kaharjan** [comment]
Thank you, if so I will stick to  AnkiDesktop(Version 2.1.19), right now AnkiDroid (2.12.1)  works really perfect, I am still very happy!!! 
Thank you very much!!!

**Comment by kuklinistvan** [comment]
Not at all. Good luck :)
