### ISSUE TITLE
SyncRedirector no longer works for lastest anki version 

### ISSUE THREAD

**Issue by pluveto** [ankicommunity/docker-anki-sync-server#7]
* **AnkiDesktop version number:** 2.1.33

## Summary

From https://ankiweb.net/shared/info/2124817646
```
Supported Anki versions:
2.1.19
```
And it's unable to install this by Addons Manager of Anki

**Comment by kuklinistvan** [comment]
Hello,

I've just updated the [README](https://github.com/ankicommunity/docker-anki-sync-server/blob/0d6f29deb1c31330059717e6ceab3c5fdcc9dbfd/README.md#news) - you can learn more about the reasons of this problem there.

We have contributors working on newer servers right now, stay tuned and follow us on [Gitter](https://gitter.im/ankicommunity/community)!

Feel free to reopen this issue of you have further questions or suggestions!
